-- Schema setup and sequence adjustments

-- Create sequence objects for each table
CREATE SEQUENCE IF NOT EXISTS user_seq START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS role_seq START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS address_seq START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS product_seq START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS category_seq START WITH 10 INCREMENT BY 1; 